# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/danie/Dropbox/physics/UdeC/experimento decoy/FPGA/FPGA2_measurement/nexysA7_driver_PM/nexysA7_driver_PM.srcs/sources_1/ip/MemTx_8x1024/MemTx_8x1024.xci
# IP: The module: 'MemTx_8x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Dropbox/physics/UdeC/experimento decoy/FPGA/FPGA2_measurement/nexysA7_driver_PM/nexysA7_driver_PM.gen/sources_1/ip/MemTx_8x1024/MemTx_8x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemTx_8x1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/danie/Dropbox/physics/UdeC/experimento decoy/FPGA/FPGA2_measurement/nexysA7_driver_PM/nexysA7_driver_PM.srcs/sources_1/ip/MemTx_8x1024/MemTx_8x1024.xci
# IP: The module: 'MemTx_8x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Dropbox/physics/UdeC/experimento decoy/FPGA/FPGA2_measurement/nexysA7_driver_PM/nexysA7_driver_PM.gen/sources_1/ip/MemTx_8x1024/MemTx_8x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemTx_8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
